import {
    FaUsers,
    FaUserPlus,
    FaKitMedical,
    FaUserCheck,
} from "react-icons/fa6";

import patientsData from "../../data/patientsData";

export const patientsStatus = [
    { id: "MCP001", status: "Admitted" },
    { id: "MCP002", status: "OP" },
    { id: "MCP003", status: "Discharged" },
    { id: "MCP004", status: "OP" },
    { id: "MCP005", status: "Admitted" },
    { id: "MCP006", status: "OP" },
    { id: "MCP007", status: "OP" },
    { id: "MCP008", status: "Discharged" },
    { id: "MCP009", status: "Admitted" },
    { id: "MCP010", status: "OP" },

    { id: "MCP011", status: "OP" },
    { id: "MCP012", status: "Admitted" },
    { id: "MCP013", status: "Discharged" },
    { id: "MCP014", status: "OP" },
    { id: "MCP015", status: "Admitted" },
    { id: "MCP016", status: "OP" },
    { id: "MCP017", status: "Discharged" },
    { id: "MCP018", status: "Admitted" },
    { id: "MCP019", status: "OP" },
    { id: "MCP020", status: "OP" },

    { id: "MCP021", status: "Discharged" },
    { id: "MCP022", status: "Admitted" },
    { id: "MCP023", status: "OP" },
    { id: "MCP024", status: "OP" },
    { id: "MCP025", status: "Admitted" },
    { id: "MCP026", status: "Discharged" },
    { id: "MCP027", status: "OP" },
    { id: "MCP028", status: "Admitted" },
    { id: "MCP029", status: "OP" },
    { id: "MCP030", status: "Discharged" },

    { id: "MCP031", status: "OP" },
    { id: "MCP032", status: "Admitted" },
    { id: "MCP033", status: "OP" },
    { id: "MCP034", status: "Discharged" },
    { id: "MCP035", status: "Admitted" },
    { id: "MCP036", status: "OP" },
    { id: "MCP037", status: "OP" },
    { id: "MCP038", status: "Admitted" },
    { id: "MCP039", status: "Discharged" },
    { id: "MCP040", status: "OP" },

    { id: "MCP041", status: "Admitted" },
    { id: "MCP042", status: "OP" },
    { id: "MCP043", status: "Discharged" },
    { id: "MCP044", status: "OP" },
    { id: "MCP045", status: "Admitted" },
    { id: "MCP046", status: "OP" },
    { id: "MCP047", status: "Discharged" },
    { id: "MCP048", status: "Admitted" },
    { id: "MCP049", status: "OP" },
    { id: "MCP050", status: "OP" },

    { id: "MCP051", status: "Discharged" },
    { id: "MCP052", status: "Admitted" },
    { id: "MCP053", status: "OP" },
    { id: "MCP054", status: "Admitted" },
    { id: "MCP055", status: "OP" },
    { id: "MCP056", status: "Discharged" },
    { id: "MCP057", status: "OP" },
    { id: "MCP058", status: "Admitted" },
    { id: "MCP059", status: "OP" },
    { id: "MCP060", status: "Discharged" },

    { id: "MCP061", status: "Admitted" },
    { id: "MCP062", status: "OP" },
    { id: "MCP063", status: "OP" },
    { id: "MCP064", status: "Discharged" },
    { id: "MCP065", status: "Admitted" },
    { id: "MCP066", status: "OP" },
    { id: "MCP067", status: "Discharged" },
    { id: "MCP068", status: "OP" },
    { id: "MCP069", status: "Admitted" },
    { id: "MCP070", status: "OP" },

    { id: "MCP071", status: "Discharged" },
    { id: "MCP072", status: "Admitted" },
    { id: "MCP073", status: "OP" },
    { id: "MCP074", status: "OP" },
    { id: "MCP075", status: "Admitted" },
    { id: "MCP076", status: "Discharged" },
    { id: "MCP077", status: "OP" },
    { id: "MCP078", status: "Admitted" },
    { id: "MCP079", status: "OP" },
    { id: "MCP080", status: "Discharged" },
    
    { id: "MCP081", status: "OP" },
    { id: "MCP082", status: "Admitted" },
    { id: "MCP083", status: "Discharged" },
    { id: "MCP084", status: "OP" },
    { id: "MCP085", status: "Admitted" },
    { id: "MCP086", status: "OP" },
    { id: "MCP087", status: "Discharged" },
    { id: "MCP088", status: "OP" },
    { id: "MCP089", status: "Admitted" },
    { id: "MCP090", status: "OP" },

    { id: "MCP091", status: "Discharged" },
    { id: "MCP092", status: "Admitted" },
    { id: "MCP093", status: "OP" },
    { id: "MCP094", status: "OP" },
    { id: "MCP095", status: "Admitted" },
    { id: "MCP096", status: "Discharged" },
    { id: "MCP097", status: "OP" },
    { id: "MCP098", status: "Admitted" },
    { id: "MCP099", status: "OP" },
    { id: "MCP100", status: "Discharged" },

    { id: "MCP101", status: "Admitted" },
    { id: "MCP102", status: "OP" },
    { id: "MCP103", status: "OP" },
    { id: "MCP104", status: "Discharged" },
    { id: "MCP105", status: "Admitted" },
    { id: "MCP106", status: "OP" },
    { id: "MCP107", status: "Discharged" },
    { id: "MCP108", status: "Admitted" },
    { id: "MCP109", status: "OP" },
    { id: "MCP110", status: "OP" },

    { id: "MCP111", status: "Discharged" },
    { id: "MCP112", status: "Admitted" },
    { id: "MCP113", status: "OP" },
    { id: "MCP114", status: "Admitted" },
    { id: "MCP115", status: "OP" },
    { id: "MCP116", status: "Discharged" },
    { id: "MCP117", status: "OP" },
    { id: "MCP118", status: "Admitted" },
    { id: "MCP119", status: "OP" },
    { id: "MCP120", status: "Discharged" },

    { id: "MCP121", status: "Admitted" },
    { id: "MCP122", status: "OP" },
    { id: "MCP123", status: "Discharged" },
    { id: "MCP124", status: "OP" },
    { id: "MCP125", status: "Admitted" },
    { id: "MCP126", status: "OP" },
    { id: "MCP127", status: "OP" },
    { id: "MCP128", status: "Discharged" },
    { id: "MCP129", status: "Admitted" },
    { id: "MCP130", status: "OP" },

    { id: "MCP131", status: "Discharged" },
    { id: "MCP132", status: "OP" },
    { id: "MCP133", status: "Admitted" },
    { id: "MCP134", status: "OP" },
    { id: "MCP135", status: "Discharged" },
    { id: "MCP136", status: "Admitted" },
    { id: "MCP137", status: "OP" },
    { id: "MCP138", status: "OP" },
    { id: "MCP139", status: "Discharged" },
    { id: "MCP140", status: "Admitted" },

    { id: "MCP141", status: "OP" },
    { id: "MCP142", status: "Discharged" },
    { id: "MCP143", status: "Admitted" },
    { id: "MCP144", status: "OP" },
    { id: "MCP145", status: "Admitted" },
    { id: "MCP146", status: "Discharged" },
    { id: "MCP147", status: "OP" },
    { id: "MCP148", status: "Admitted" },
    { id: "MCP149", status: "OP" },
    { id: "MCP150", status: "Discharged" },

    { id: "MCP151", status: "OP" },
    { id: "MCP152", status: "Admitted" },
    { id: "MCP153", status: "Discharged" },
    { id: "MCP154", status: "OP" },
    { id: "MCP155", status: "Admitted" },
    { id: "MCP156", status: "OP" },
    { id: "MCP157", status: "Discharged" },
    { id: "MCP158", status: "Admitted" },
    { id: "MCP159", status: "OP" },
    { id: "MCP160", status: "OP" },

    { id: "MCP161", status: "Discharged" },
    { id: "MCP162", status: "Admitted" },
    { id: "MCP163", status: "OP" },
    { id: "MCP164", status: "OP" },
    { id: "MCP165", status: "Admitted" },
    { id: "MCP166", status: "Discharged" },
    { id: "MCP167", status: "OP" },
    { id: "MCP168", status: "Admitted" },
    { id: "MCP169", status: "OP" },
    { id: "MCP170", status: "Discharged" },

    { id: "MCP171", status: "Admitted" },
    { id: "MCP172", status: "OP" },
    { id: "MCP173", status: "Discharged" },
    { id: "MCP174", status: "Discharged" },
    { id: "MCP175", status: "Admitted" },
    { id: "MCP176", status: "OP" },
    { id: "MCP177", status: "OP" },
    { id: "MCP178", status: "Discharged" },
    { id: "MCP179", status: "Admitted" },
    { id: "MCP180", status: "OP" },

    { id: "MCP181", status: "Discharged" },
    { id: "MCP182", status: "Admitted" },
    { id: "MCP183", status: "OP" },
    { id: "MCP184", status: "OP" },
    { id: "MCP185", status: "Discharged" },
    { id: "MCP186", status: "Admitted" },
    { id: "MCP187", status: "OP" },
    { id: "MCP188", status: "Discharged" },
    { id: "MCP189", status: "Admitted" },
    { id: "MCP190", status: "OP" },

    { id: "MCP191", status: "OP" },
    { id: "MCP192", status: "Admitted" },
    { id: "MCP193", status: "Discharged" },
    { id: "MCP194", status: "OP" },
    { id: "MCP195", status: "Admitted" },
    { id: "MCP196", status: "OP" },
    { id: "MCP197", status: "Discharged" },
    { id: "MCP198", status: "Admitted" },
    { id: "MCP199", status: "OP" },
    { id: "MCP200", status: "Discharged" },

    { id: "MCP201", status: "Admitted" },
    { id: "MCP202", status: "OP" },
    { id: "MCP203", status: "Discharged" },
    { id: "MCP204", status: "OP" },
    { id: "MCP205", status: "Admitted" },
    { id: "MCP206", status: "OP" },
    { id: "MCP207", status: "Discharged" },
    { id: "MCP208", status: "Admitted" },
    { id: "MCP209", status: "OP" },
    { id: "MCP210", status: "Discharged" },

    { id: "MCP211", status: "Discharged" },
    { id: "MCP212", status: "Admitted" },
    { id: "MCP213", status: "OP" },
    { id: "MCP214", status: "Discharged" },
    { id: "MCP215", status: "Admitted" },
    { id: "MCP216", status: "OP" },
    { id: "MCP217", status: "OP" },
    { id: "MCP218", status: "Discharged" },
    { id: "MCP219", status: "Admitted" },
    { id: "MCP220", status: "OP" },

    { id: "MCP221", status: "Discharged" },
    { id: "MCP222", status: "Admitted" },
    { id: "MCP223", status: "OP" },
    { id: "MCP224", status: "Discharged" },
];


const statusMap = Object.fromEntries(
    patientsStatus.map((patient) => [patient.id, patient.status])
);

export const patientsPageRecords = patientsData.map((patient) => ({
    ...patient,
    status: statusMap[patient.id] || "OP",
}));

const admittedCount = patientsPageRecords.filter(
    (patient) => patient.status === "Admitted"
).length;

const dischargedCount = patientsPageRecords.filter(
    (patient) => patient.status === "Discharged"
).length;

const opCount = patientsPageRecords.filter(
    (patient) => patient.status === "OP"
).length;

export const patientsPageStats = [
    {
        id: 1,
        title: "Total Patients",
        value: dischargedCount + opCount + admittedCount,
        icon: FaUsers,
        growth: `${dischargedCount} discharged records`,
    },
    {
        id: 2,
        title: "Admitted Patients",
        value: admittedCount,
        icon: FaUserPlus,
        growth: `${admittedCount} currently admitted`,
    },
    {
        id: 3,
        title: "Outpatients (OP)",
        value: opCount,
        icon: FaKitMedical,
        growth: `${opCount} outpatient records`,
    },
    {
        id: 4,
        title: "Discharged Patients",
        value: dischargedCount,
        icon: FaUserCheck,
        growth: `${dischargedCount} discharged records`,
    },
    
];