const notifications = [
  {
    id: 1,
    type: "info",
    title: "New patient admitted",
    message: "Rahul Kumar has been admitted to the Cardiology department.",
    time: "2 min ago",
    unread: true,
  },
  {
    id: 2,
    type: "emergency",
    title: "Code Blue activated",
    message: "ICU Ward B requires immediate medical assistance.",
    time: "4 min ago",
    unread: true,
  },
  {
    id: 3,
    type: "alert",
    title: "Low stock: Paracetamol injection",
    message: "Pharmacy inventory is below the reorder level.",
    time: "8 min ago",
    unread: true,
  },
  {
    id: 4,
    type: "info",
    title: "Appointment confirmed",
    message: "Appointment with Dr. Meera Nair confirmed for 3:30 PM.",
    time: "12 min ago",
    unread: false,
  },
  {
    id: 5,
    type: "alert",
    title: "OPD waiting time exceeded",
    message: "Average waiting time has crossed 45 minutes in General OPD.",
    time: "18 min ago",
    unread: false,
  },
  {
    id: 6,
    type: "emergency",
    title: "Emergency patient arriving",
    message: "Trauma patient expected in Emergency Block within 3 minutes.",
    time: "22 min ago",
    unread: false,
  },
  {
    id: 7,
    type: "info",
    title: "Billing report generated",
    message: "The daily billing summary has been generated successfully.",
    time: "30 min ago",
    unread: false,
  },
  {
    id: 8,
    type: "alert",
    title: "MRI maintenance scheduled",
    message: "MRI Machine 2 will be unavailable from 6:00 PM to 8:00 PM.",
    time: "42 min ago",
    unread: false,
  },
  {
    id: 9,
    type: "info",
    title: "Staff meeting scheduled",
    message: "Administration meeting scheduled today at 4:00 PM.",
    time: "55 min ago",
    unread: false,
  },
  {
    id: 10,
    type: "emergency",
    title: "Blood bank stock critical",
    message: "O-negative blood units have fallen below the minimum threshold.",
    time: "1 hour ago",
    unread: false,
  },
  {
    id: 11,
    type: "alert",
    title: "Pending appointments",
    message: "Dr. Priya Sharma has 4 unconfirmed appointments today.",
    time: "1 hour ago",
    unread: false,
  },
  {
    id: 12,
    type: "info",
    title: "New nurse assigned",
    message: "Nurse Anjali has been assigned to ICU Night Shift.",
    time: "1 hour ago",
    unread: false,
  },
  {
    id: 13,
    type: "alert",
    title: "Bed occupancy warning",
    message: "Hospital bed occupancy has reached 92%.",
    time: "2 hours ago",
    unread: false,
  },
  {
    id: 14,
    type: "emergency",
    title: "Ventilator alarm triggered",
    message: "ICU Bed 3 ventilator requires immediate inspection.",
    time: "2 hours ago",
    unread: false,
  },
  {
    id: 15,
    type: "info",
    title: "Insurance claim approved",
    message: "Insurance claim for patient ID MC-2045 has been approved.",
    time: "3 hours ago",
    unread: false,
  },
  {
    id: 16,
    type: "alert",
    title: "Laboratory delay detected",
    message: "Blood test reports are delayed by approximately 25 minutes.",
    time: "3 hours ago",
    unread: false,
  },
  {
    id: 17,
    type: "info",
    title: "Vaccination drive begins tomorrow",
    message: "Community vaccination program starts tomorrow at 9:00 AM.",
    time: "5 hours ago",
    unread: false,
  },
  {
    id: 18,
    type: "alert",
    title: "Oxygen cylinder replacement",
    message: "Ward C oxygen supply requires cylinder replacement.",
    time: "6 hours ago",
    unread: false,
  },
  {
    id: 19,
    type: "info",
    title: "Discharge summary uploaded",
    message: "Discharge documents for patient Priya Reddy are now available.",
    time: "Yesterday, 6:15 PM",
    unread: false,
  },
  {
    id: 20,
    type: "alert",
    title: "Pharmacy audit reminder",
    message: "Monthly pharmacy inventory audit is due by 5:00 PM.",
    time: "Yesterday, 4:40 PM",
    unread: false,
  },
];

export default notifications;